export const Users = [
    {
      id:1,
      profilePicture: "assets/beach.jpg",
      username: "Samaria Shah",
    },
    {
      id:2,
      profilePicture: "assets/profile.png",
      username: "Jenny Bay",
    },
    {
      id:3,
      profilePicture:  "assets/profile.png",
      username: "Ananya Awasthi",
    },
    {
      id:4,
      profilePicture:  "assets/profile.png",
      username: "Navya Roy",
    },
    {
      id:5,
      profilePicture:  "assets/profile.png",
      username: "Eshan Maidan",
    },
    {
      id:6,
      profilePicture:  "assets/profile.png",
      username: "Saroj Simpson",
    },
    {
      id:7,
      profilePicture: "assets/profile.png",
      username: "Himani Verma",
    },
    {
      id:8,
      profilePicture: "assets/profile.png",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "assets/profile.png",
      username: "Gareema Wadhwa",
    },
    {
      id:10,
      profilePicture:  "assets/profile.png",
      username: "Harsh Vijay",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/beach.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/nature.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/fountain.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/fountain.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/beach.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/fountain.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo:"assets/beach.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/nature.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/beach.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/fountain.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];